/// DescriptorMacroGen — descriptor_macros.glsl 生成器
///
/// 唯一输入：inc/hgl/common/DescriptorSetTypeDef.h 的 kDescriptorBindingMacros 规范表
///（绑定号数值真源为同文件 SceneBinding/PerObjectBinding 枚举）。
///
/// 用法：
///   DescriptorMacroGen --emit            向 stdout 输出完整 descriptor_macros.glsl（CRLF）
///   DescriptorMacroGen --verify <path>   生成内容与指定文件比对（忽略行尾差异）
///
/// ShaderLibrary/common/descriptor_macros.glsl 是生成物，禁止手改；
/// 绑定号/宏变更入口在 DescriptorSetTypeDef.h，改后运行本工具重新生成。
/// --verify 已接入 ctest（VerifyDescriptorMacros），漂移会在构建期暴露。
///
/// 参见：ShaderGen_Descriptor_ABI_Unification_Plan.md Phase 2

#include <hgl/common/DescriptorSetTypeDef.h>
#include <hgl/mtl/DescriptorResourceCatalog.h>

#include <cstdio>
#include <cstring>
#include <string>
#include <io.h>
#include <fcntl.h>

namespace
{
    using hgl::graph::DescriptorMacroKind;
    using hgl::graph::kDescriptorBindingMacros;
    using hgl::graph::DescriptorSetType;
    using hgl::graph::GetDescriptorSetTypeName;
    using hgl::graph::mtl::kDescriptorResourceCatalog;
    using hgl::graph::mtl::DescriptorResourceCatalogEntry;
    using hgl::graph::mtl::ResourceCatalogClass;

    // 文件头（@ulre 元数据块为 GLSLCodeModuleRegistry 解析所必需，原样保留）
    constexpr const char *FILE_PREAMBLE =
        "// GENERATED by DescriptorMacroGen — DO NOT EDIT\n"
        "// 数值真源：inc/hgl/common/DescriptorSetTypeDef.h（SceneBinding/PerObjectBinding 枚举 + kDescriptorBindingMacros 规范表）\n"
        "// 重新生成：DescriptorMacroGen --emit > ShaderLibrary/common/descriptor_macros.glsl\n"
        "// @ulre begin\n"
        "// @ulre name descriptor_macros\n"
        "// @ulre kind Utility\n"
        "// @ulre priority 0\n"
        "// @ulre end\n"
        "// descriptor_macros.glsl — 标准描述符集/绑定宏定义\n"
        "//\n"
        "// 默认值对应 3D 标准布局（Scene=0, PerObject=1, Material=2, Bindless=3）。\n"
        "// 2D 生成器或自定义材质可在 #include 之前 #define 覆盖默认值。\n"
        "//\n"
        "// 固定布局：set 间按 Scene(0) < PerObject(1) < Material(2) < Bindless(3)。\n"
        "// 行表 SSBO 声明（mtl_private_data_index / mtl_texture_layer_rows / l2w_index_rows）\n"
        "// 不在此定义默认值：由 CompileCompositorMaterial 依据 descriptor_info 统一生成并\n"
        "// 注入（buffer 声明 + Resolve 函数，不再写死在 .glsl）。\n"
        "// 材质实例 mtl SSBO 的 struct/buffer 声明同样由 CompileCompositorMaterial 统一生成并注入。\n"
        "\n"
        "#ifndef DESCRIPTOR_MACROS_GLSL\n"
        "#define DESCRIPTOR_MACROS_GLSL\n";

    constexpr const char *FILE_EPILOGUE = "\n#endif // DESCRIPTOR_MACROS_GLSL\n";

    // 以 '\n' 行尾生成全部内容
    std::string GenerateGLSL()
    {
        std::string out(FILE_PREAMBLE);

        for (const auto &spec : kDescriptorBindingMacros)
        {
            if (spec.blank_before)
                out += '\n';

            if (spec.comment)
            {
                out += spec.comment;
                out += '\n';

                if (spec.blank_after_comment)
                    out += '\n';
            }

            out += "#ifndef ";
            out += spec.name;
            out += "\n#define ";
            out += spec.name;
            out += ' ';

            switch (spec.kind)
            {
            case DescriptorMacroKind::SetIndex:
                out += std::to_string(int(spec.set_type));
                break;

            case DescriptorMacroKind::SetAlias:
                out += spec.alias_target;
                break;

            case DescriptorMacroKind::Binding:
                out += std::to_string(spec.binding);
                break;
            }

            out += "\n#endif\n";
        }

        out += FILE_EPILOGUE;
        return out;
    }

    std::string ToCRLF(const std::string &src)
    {
        std::string out;
        out.reserve(src.size() + src.size() / 8);

        for (const char c : src)
        {
            if (c == '\n')
                out += "\r\n";
            else
                out += c;
        }

        return out;
    }

    // 忽略行尾差异（\r\n 与 \n 等价），使校验不受 git 检出行尾策略影响
    std::string NormalizeEOL(const std::string &src)
    {
        std::string out;
        out.reserve(src.size());

        for (size_t i = 0; i < src.size(); ++i)
        {
            if (src[i] == '\r')
                continue;
            out += src[i];
        }

        return out;
    }

    bool ReadTextFile(const char *filename, std::string &out)
    {
        FILE *fp = std::fopen(filename, "rb");
        if (!fp)
            return false;

        char buf[4096];
        size_t n;
        while ((n = std::fread(buf, 1, sizeof(buf), fp)) > 0)
            out.append(buf, n);

        std::fclose(fp);
        return true;
    }

    // ── 目录 ↔ 宏规范表 交叉覆盖校验（S1-T1.5）────────────────────────────────
    //
    // kDescriptorResourceCatalog（mtl 层）与 kDescriptorBindingMacros（common 层）
    // 都从 SceneBinding/VertexBinding 等枚举取绑定号，故**数值**不会各自漂移；
    // 真正的缺口是**覆盖**：新增一条顶点/全局资源却忘记加 GLSL 默认宏 → shader 侧
    // 无法按宏引用该 binding。分层禁止 common 依赖 mtl，故该断言只能落在同时可见
    // 两者的工具侧（本工具已链 ULRE.ShaderGen）。
    //
    // 参与检查的类别：VertexGeometry（几何 ABI，s1_* 模块按宏声明 binding）与
    // SceneGlobal（全局 UBO）。不参与：PerDraw 行表类（l2w_index/private_data_index
    // 的 buffer 声明由 CompileCompositorMaterial 生成注入，无默认宏）、MaterialData
    // （binding=-1 per-material 动态）、以及 CharQuad 文本三 SSBO（宏侧有、目录未收录，
    // 属 mesh 模式内部约定，非通用资源）。
    bool NeedsGLSLBindingMacro(const DescriptorResourceCatalogEntry &row)
    {
        return (row.cls == ResourceCatalogClass::VertexGeometry
             || row.cls == ResourceCatalogClass::SceneGlobal)
            && row.binding >= 0;
    }

    const char *RowName(const DescriptorResourceCatalogEntry &row)
    {
        return row.sbs && row.sbs->name ? row.sbs->name : "(dynamic)";
    }

    int CrossCheckCatalogCoverage()
    {
        int fail = 0;

        // ① 目录 → 宏：每个需要宏的资源行都必须有同集同绑定号的 Binding 宏
        for (const DescriptorResourceCatalogEntry &row : kDescriptorResourceCatalog)
        {
            if (!NeedsGLSLBindingMacro(row))
                continue;

            bool found = false;

            for (const auto &spec : kDescriptorBindingMacros)
                if (spec.kind == DescriptorMacroKind::Binding
                 && spec.set_type == row.set_type
                 && spec.binding == row.binding)
                {
                    found = true;
                    break;
                }

            if (!found)
            {
                std::fprintf(stderr,
                    "[DescriptorMacroGen] 资源目录行缺少 GLSL binding 宏: %s (set=%s binding=%d)\n"
                    "  → 在 inc/hgl/common/DescriptorSetTypeDef.h 的 kDescriptorBindingMacros 补一行\n",
                    RowName(row), GetDescriptorSetTypeName(row.set_type), row.binding);
                ++fail;
            }
        }

        // ② 宏 → 目录（仅 Vertex 集：几何 ABI 要求宏与目录一一对应）
        for (const auto &spec : kDescriptorBindingMacros)
        {
            if (spec.kind != DescriptorMacroKind::Binding
             || spec.set_type != DescriptorSetType::Vertex)
                continue;

            bool found = false;

            for (const DescriptorResourceCatalogEntry &row : kDescriptorResourceCatalog)
                if (row.set_type == DescriptorSetType::Vertex
                 && row.binding == spec.binding)
                {
                    found = true;
                    break;
                }

            if (!found)
            {
                std::fprintf(stderr,
                    "[DescriptorMacroGen] Vertex 宏 %s (binding=%d) 在资源目录无对应行\n"
                    "  → 在 inc/hgl/mtl/DescriptorResourceCatalog.h 登记该顶点资源\n",
                    spec.name, spec.binding);
                ++fail;
            }
        }

        if (fail > 0)
            std::fprintf(stderr,
                "[DescriptorMacroGen] 交叉校验失败 %d 项"
                "（资源目录与 GLSL 宏规范表覆盖不一致）\n", fail);

        return fail;
    }

    int Verify(const char *filename)
    {
        if (CrossCheckCatalogCoverage() > 0)
            return 4;

        std::string disk;
        if (!ReadTextFile(filename, disk))
        {
            std::fprintf(stderr, "[DescriptorMacroGen] cannot read file: %s\n", filename);
            return 2;
        }

        const std::string generated = NormalizeEOL(GenerateGLSL());
        const std::string on_disk   = NormalizeEOL(disk);

        if (generated == on_disk)
        {
            std::printf("[DescriptorMacroGen] verify OK: %s\n", filename);
            return 0;
        }

        size_t line = 1, pos = 0;
        while (pos < generated.size() && pos < on_disk.size()
            && generated[pos] == on_disk[pos])
        {
            if (generated[pos] == '\n')
                ++line;
            ++pos;
        }

        std::fprintf(stderr,
            "[DescriptorMacroGen] MISMATCH: %s line %zu\n"
            "  generated: %.96s\n"
            "  on disk  : %.96s\n"
            "\n"
            "descriptor_macros.glsl 是生成物，禁止手改。\n"
            "如需变更：修改 inc/hgl/common/DescriptorSetTypeDef.h 的枚举/规范表，\n"
            "再运行 DescriptorMacroGen --emit 重新生成。\n",
            filename, line,
            generated.c_str() + pos,
            on_disk.c_str() + pos);
        return 1;
    }
}//namespace

int main(int argc, char **argv)
{
    if (argc >= 2 && std::strcmp(argv[1], "--emit") == 0)
    {
        // 覆盖不一致时拒绝发射（避免把不自洽的 .glsl 写进仓库）
        if (CrossCheckCatalogCoverage() > 0)
            return 4;

        // 文本模式会把 "\r\n" 再翻译成 "\r\r\n"，必须切二进制输出
        _setmode(_fileno(stdout), _O_BINARY);

        const std::string crlf = ToCRLF(GenerateGLSL());
        std::fwrite(crlf.data(), 1, crlf.size(), stdout);
        return 0;
    }

    if (argc >= 3 && std::strcmp(argv[1], "--verify") == 0)
        return Verify(argv[2]);

    std::fprintf(stderr,
        "usage:\n"
        "  DescriptorMacroGen --emit            输出 descriptor_macros.glsl 到 stdout\n"
        "  DescriptorMacroGen --verify <path>   校验文件与规范表一致\n");
    return 3;
}
