#ifndef ULRE_SURFACE_2D_PURETEXTURE2D_SURFACE_GLSL
#define ULRE_SURFACE_2D_PURETEXTURE2D_SURFACE_GLSL

// ──────────────────────────────────────────────────────────────────────────
// puretexture2d_surface.glsl — Pure texture 2D surface function.
//
// Sampler declaration and getter (GetSamplerBaseColor) are generated by
// C++ SimpleSamplerGLSLEmitter at compile time, supporting:
//   Standard, Texture Array, Atlas, and other TextureSourceModes.
// ──────────────────────────────────────────────────────────────────────────

#include "common/surface_interface.glsl"

SurfaceOutput EvalSurface(SurfaceInput si)
{
    vec4 color = GetSamplerBaseColor(si.uv0);

    SurfaceOutput so;
    so.baseColor = color.rgb;
    so.alpha     = color.a;
    so.normal    = vec3(0.0, 0.0, 1.0);
    so.metallic  = 0.0;
    so.roughness = 1.0;
    so.ao        = 1.0;
    so.emissive  = vec3(0.0);
    return so;
}

float EvalAlpha(SurfaceInput si)
{
    return GetSamplerBaseColor(si.uv0).a;
}

#endif // ULRE_SURFACE_2D_PURETEXTURE2D_SURFACE_GLSL
