// ──────────────────────────────────────────────────────────────────────────
// text2d_surface.glsl — Text 2D surface function.
//
// Sampler declaration and getter (GetSamplerText) are generated by
// C++ SimpleSamplerGLSLEmitter at compile time.
// Text color is stored as a packed uint in the MaterialInstance SSBO.
// ──────────────────────────────────────────────────────────────────────────

#include "common/surface_interface.glsl"

#include "common/ssbo_material_instance.glsl"

SurfaceOutput EvalSurface(SurfaceInput si)
{
    MaterialInstance mi = GetMaterialInstance();
    vec4 textColor = unpackUnorm4x8(mi.TextColor);

    float lum = GetSamplerText(si.uv0).r;

    SurfaceOutput so;
    so.baseColor = textColor.rgb * lum;
    so.alpha     = textColor.a;
    so.normal    = vec3(0.0, 0.0, 1.0);
    so.metallic  = 0.0;
    so.roughness = 1.0;
    so.ao        = 1.0;
    so.emissive  = vec3(0.0);
    return so;
}

float EvalAlpha(SurfaceInput si)
{
    MaterialInstance mi = GetMaterialInstance();
    return unpackUnorm4x8(mi.TextColor).a;
}
