// Phase0GoldenDump
//
// Exports selected built-in variant assembled GLSL snapshots to:
//   doc/refactor/golden/phase0/<variant>/vertex.glsl
//   doc/refactor/golden/phase0/<variant>/fragment.glsl
//   doc/refactor/golden/phase0/<variant>/meta.json
// and writes an index at:
//   doc/refactor/golden/phase0/index.md

#include <hgl/shadergen/CompositorAssembler.h>
#include <hgl/shadergen/GLSLCompilerConfig.h>
#include <hgl/mtl/MaterialVariantKey.h>
#include <hgl/mtl/SamplerSlot.h>

#include "../BuiltinVariantEntry.h"

#include <array>
#include <cstddef>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <string>
#include <string_view>
#include <vector>

using namespace hgl::graph;
using namespace hgl::graph::mtl;

namespace {

struct DumpRow
{
    std::string name;
    std::string hash_hex;
    std::string tex_summary;
    int surface_type = 0;
    int geometry_mode = 0;
    int blend_mode = 0;
    int pass_hint = 0;
};

constexpr std::array<const char *, 13> kPhase0CandidateNames = {
    "VertexColor2D",
    "PureTexture2D",
    "Text2D",
    "Billboard2DDynamic",
    "Billboard2DDynamicMasked",
    "Billboard2DFixedA2C",
    "TerrainGrid",
    "SkyMinimal",
    "Standard",
    "StandardBlinnPhong",
    "StandardTextureArray",
    "PBRColor3D",
    "FullscreenTriangle",
};

std::string Hex64(const uint64_t v)
{
    char buf[32] = {};
    std::snprintf(buf, sizeof(buf), "0x%016llX", static_cast<unsigned long long>(v));
    return std::string(buf);
}

const char *TextureModeName(const TextureSourceMode mode)
{
    switch (mode)
    {
        case TextureSourceMode::None:   return "None";
        case TextureSourceMode::Simple: return "Simple";
        case TextureSourceMode::Array:  return "Array";
        case TextureSourceMode::Atlas:  return "Atlas";
        case TextureSourceMode::PCG:    return "PCG";
        default:                        return "Unknown";
    }
}

const BuiltinVariantEntry *FindBuiltinByName(const std::string_view name)
{
    for (size_t i = 0; i < kBuiltinVariantsCount; ++i)
    {
        if (kBuiltinVariants[i].name && std::string_view(kBuiltinVariants[i].name) == name)
            return &kBuiltinVariants[i];
    }

    return nullptr;
}

bool WriteTextFile(const std::filesystem::path &path, const std::string &text)
{
    std::error_code ec;
    std::filesystem::create_directories(path.parent_path(), ec);
    if (ec)
        return false;

    std::ofstream out(path, std::ios::binary | std::ios::trunc);
    if (!out.is_open())
        return false;

    out.write(text.data(), static_cast<std::streamsize>(text.size()));
    return static_cast<bool>(out);
}

std::string BuildTextureSourceSummary(const MaterialVariantKey &key)
{
    std::string text;

    for (uint8_t i = 0; i < static_cast<uint8_t>(SamplerSlot::RANGE_SIZE); ++i)
    {
        const SamplerSlot slot = static_cast<SamplerSlot>(i);
        const TextureSourceMode mode = key.GetTextureSourceMode(slot);

        if (mode == TextureSourceMode::None)
            continue;

        if (!text.empty())
            text += ", ";

        text += SamplerSlotNameList[i];
        text += ':';
        text += TextureModeName(mode);
    }

    if (text.empty())
        return "<none>";

    return text;
}

std::string BuildMetaJson(const std::string &name,
                          const MaterialVariantKey &key,
                          const MaterialVariantDesc &desc)
{
    std::string json;
    json += "{\n";
    json += "  \"variant_name\": \"" + name + "\",\n";
    json += "  \"key_hash\": \"" + Hex64(key.Hash()) + "\",\n";
    json += "  \"surface_type\": " + std::to_string(static_cast<int>(key.surface_type)) + ",\n";
    json += "  \"geometry_mode\": " + std::to_string(static_cast<int>(key.geometry_mode)) + ",\n";
    json += "  \"blend_mode\": " + std::to_string(static_cast<int>(key.blend_mode)) + ",\n";
    json += "  \"pass_hint\": " + std::to_string(static_cast<int>(key.pass_hint)) + ",\n";
    json += "  \"vs_template_path\": \"" + desc.vs_template_path + "\",\n";
    json += "  \"fs_template_path\": \"" + desc.fs_template_path + "\",\n";
    json += "  \"surface_function_path\": \"" + desc.surface_function_path + "\",\n";
    json += "  \"texture_source_summary\": \"" + BuildTextureSourceSummary(key) + "\"\n";
    json += "}\n";
    return json;
}

std::string BuildIndexMarkdown(const std::vector<DumpRow> &rows)
{
    std::string md;
    md += "# ShaderGen Phase0 Golden Dump Index\n\n";
    md += "Generated by `Phase0GoldenDump`.\n\n";
    md += "| Variant | Key Hash | Surface | Geometry | Blend | Pass | Texture Source Summary |\n";
    md += "| --- | --- | ---: | ---: | ---: | ---: | --- |\n";

    for (const auto &r : rows)
    {
        md += "| " + r.name
           + " | " + r.hash_hex
           + " | " + std::to_string(r.surface_type)
           + " | " + std::to_string(r.geometry_mode)
           + " | " + std::to_string(r.blend_mode)
           + " | " + std::to_string(r.pass_hint)
           + " | " + r.tex_summary
           + " |\n";
    }

    md += "\n## Output Structure\n\n";
    md += "- `doc/refactor/golden/phase0/<variant>/vertex.glsl`\n";
    md += "- `doc/refactor/golden/phase0/<variant>/fragment.glsl`\n";
    md += "- `doc/refactor/golden/phase0/<variant>/meta.json`\n";
    return md;
}

} // namespace

int main(int argc, char **argv)
{
    const std::filesystem::path repo_root = (argc >= 2)
        ? std::filesystem::path(argv[1])
        : std::filesystem::current_path();

    const std::filesystem::path out_root = repo_root / "doc" / "refactor" / "golden" / "phase0";

    std::vector<DumpRow> rows;
    rows.reserve(kPhase0CandidateNames.size());

    const ShaderCompilerContext shader_context = CaptureShaderCompilerContext();
    CompositorAssembler assembler(shader_context.shader_library_path);
    int failures = 0;

    for (const char *name : kPhase0CandidateNames)
    {
        const BuiltinVariantEntry *entry = FindBuiltinByName(name);
        if (!entry)
        {
            std::fprintf(stderr, "[Phase0GoldenDump] missing builtin entry: %s\n", name);
            ++failures;
            continue;
        }

        const MaterialVariantKey key = BuildKey(*entry);
        const MaterialVariantDesc desc = BuildDesc(*entry);
        const auto assembled = assembler.Assemble(key, desc);

        if (!assembled.success)
        {
            std::fprintf(stderr,
                         "[Phase0GoldenDump] assemble failed: %s (%s)\n",
                         name,
                         assembled.error_message.c_str());
            ++failures;
            continue;
        }

        const std::filesystem::path variant_dir = out_root / name;
        const std::filesystem::path vertex_path = variant_dir / "vertex.glsl";
        const std::filesystem::path fragment_path = variant_dir / "fragment.glsl";
        const std::filesystem::path meta_path = variant_dir / "meta.json";

        if (!WriteTextFile(vertex_path, assembled.vertex_glsl)
         || !WriteTextFile(fragment_path, assembled.fragment_glsl)
         || !WriteTextFile(meta_path, BuildMetaJson(name, key, desc)))
        {
            std::fprintf(stderr, "[Phase0GoldenDump] write failed: %s\n", name);
            ++failures;
            continue;
        }

        rows.push_back(DumpRow{
            .name = name,
            .hash_hex = Hex64(key.Hash()),
            .tex_summary = BuildTextureSourceSummary(key),
            .surface_type = static_cast<int>(key.surface_type),
            .geometry_mode = static_cast<int>(key.geometry_mode),
            .blend_mode = static_cast<int>(key.blend_mode),
            .pass_hint = static_cast<int>(key.pass_hint),
        });
    }

    if (!WriteTextFile(out_root / "index.md", BuildIndexMarkdown(rows)))
    {
        std::fprintf(stderr, "[Phase0GoldenDump] write failed: index.md\n");
        ++failures;
    }

    std::printf("[Phase0GoldenDump] exported %zu variant snapshots to %s\n",
                rows.size(),
                out_root.string().c_str());

    return failures == 0 ? 0 : 1;
}
