#include "MaterialFactory3DCommon.h"
#include "Build3DCommon.h"
#include <hgl/mtl/Material3DCreateConfig.h>

namespace hgl::graph::mtl
{
namespace
{
    // No vertex entries — positions are generated from gl_VertexIndex via
    // position_provider/pcg_fullscreen_triangle.glsl; no VBO binding needed.
    const StaticMaterialDef FULLSCREEN_TRIANGLE_DEF {
        "FullscreenTriangle",
        PrimitiveType::Triangles,
        nullptr,
        0,
        nullptr,
        nullptr,
        nullptr,
        ShaderDataSchema::None,
    };

    static MaterialCreateInfo *CreateFullscreenTriangleFactory(
        const contract::PhysicalDeviceProfileLite *profile,
        const MaterialVariantDesc                 *desc,
        const MaterialVariantKey                  &key,
        MaterialCreateConfig                      *cfg)
    {
        auto *cfg_3d = static_cast<Material3DCreateConfig *>(cfg);
        Material3DCreateConfig local_cfg = cfg_3d ? *cfg_3d : Material3DCreateConfig();

        // PCG: no local-to-world, no material instance — purely procedural.
        local_cfg.local_to_world      = false;
        local_cfg.material_instance   = false;
        local_cfg.effective_feature_mask = 0;

        // VS + FS are now generated by the generic two-axis assembler:
        //   VS: position_provider/pcg_fullscreen_triangle.glsl + vertex_policy/passthrough_ndc.glsl
        //   FS: fragment_provider/pcg_fragcoord.glsl + surface/fragcoord_surface.glsl
        return CreateFromFixedDef3D("FullscreenTriangle",
                                    profile,
                                    FULLSCREEN_TRIANGLE_DEF,
                                    key,
                                    &local_cfg,
                                    *desc);
    }
}
} // namespace hgl::graph::mtl

#include "../MaterialFactory3DRegistration.h"
ULRE_REGISTER_PRESET_FACTORY(FullscreenTriangle, "FullscreenTriangle", hgl::graph::mtl::CreateFullscreenTriangleFactory)

