schema = 1
id = "DebugNormalColor"
name = "DebugNormalColor"
source = "file"
usage = "Debug"
bootstrap = "None"
provider_policy = "GeometryOnly"

[transform]
source = "Vec3Position"
mapping = "Passthrough3D"
orientation = "World"
scale = "World"
projection = "WorldCameraVP"
transport = "ssbo"

[fragment]
source = "compositor/main_forward_surface.frag.glsl"
surface_module = "surface/material_surface.glsl"
material_source_module = "material/debug_normal_source.glsl"

[compositor]
surface = "Unlit"
blend = "Opaque"
pass = "ForwardOpaque"

[vertex]
requirements = ["Position", "Normal"]
varyings = ["emit_data_index_id", "emit_world_pos", "emit_world_normal"]

[resources]
ubos = ["ViewportInfo", "CameraInfo"]
ssbos = [{ name = "mtl", type = "EmissiveSurface" }]
