schema = 1
id = "DebugNormalColor"
name = "DebugNormalColor"
source = "file"
usage = "Debug"
bootstrap = "None"
program_mode = "Compositor"
provider_policy = "GeometryOnly"

[transform]
source = "Vec3Position"
mapping = "Passthrough3D"
orientation = "World"
scale = "World"
projection = "WorldCameraVP"

[fragment]
source = "compositor/main_forward_unlit_normal.frag.glsl"
surface_module = "surface/debug_normal_color.glsl"

[compositor]
surface = "Unlit"
blend = "Opaque"
pass = "ForwardOpaque"

[vertex]
requirements = ["Position", "Normal"]
varyings = ["emit_data_index_id", "emit_texture_layer_id", "texture_layer_id_uses_data_index", "emit_world_pos", "emit_world_normal"]

[resources]
ubos = ["ViewportInfo", "CameraInfo"]
ssbos = [{ name = "mtl", type = "EmissiveSurface" }]
