schema = 1
id = "Lit"
name = "Lit"
source = "file"
usage = "General"
bootstrap = "None"
program_mode = "Compositor"
provider_policy = "GeometryOnly"

[surface_profile]
intent = "GenericPBR"
projections = [
    { profile = "StandardPBR", projection = "Lit.ToStandardPBR" },
    { profile = "BlinnPhongFakePBR", projection = "Lit.ToFakePBR" },
    { profile = "Flat", projection = "Lit.ToFlat" }
]

[transform]
source = "Vec3Position"
mapping = "Passthrough3D"
orientation = "World"
scale = "World"
projection = "WorldCameraVP"

[fragment]
source = "compositor/main_forward_surface.frag.glsl"
surface_module = "surface/material_surface.glsl"
material_source_module = "material/pbr_surface_source.glsl"
ntb_module = "ntb/ntb_tangent_vbo_normalmap.glsl"

[compositor]
surface = "Lit"
blend = "Opaque"
pass = "ForwardOpaque"

[vertex]
requirements = ["Position", "UV0", "Normal"]
varyings = ["emit_data_index_id", "emit_texture_layer_id", "texture_layer_id_uses_data_index", "emit_world_pos", "emit_world_normal", "emit_uv0"]

[resources]
ubos = ["ViewportInfo", "CameraInfo", "SkyInfo"]
code_modules = ["SkyLightHeader"]
