schema = 1
id = "Lit"
name = "Lit"
source = "file"
usage = "General"
bootstrap = "None"
program_mode = "Compositor"
provider_policy = "GeometryOnly"

[transform]
source = "Vec3Position"
mapping = "Passthrough3D"
orientation = "World"
scale = "World"
projection = "WorldCameraVP"

[fragment]
source = "compositor/main_forward_lit.frag.glsl"
surface_module = "surface/lit_surface.glsl"

[compositor]
surface = "Lit"
blend = "Opaque"
pass = "ForwardOpaque"

[vertex]
requirements = ["Position", "UV0", "Normal"]
varyings = ["emit_data_index_id", "emit_texture_layer_id", "texture_layer_id_uses_data_index", "emit_world_pos", "emit_world_normal", "emit_uv0"]

[resources]
ubos = ["ViewportInfo", "CameraInfo", "SkyInfo"]
code_modules = ["SkyLightHeader", "PBRSurface"]
ssbos = [{ name = "mtl", type = "PBRSurface" }]
textures = [
  { slot = "BaseColor", sampler = "Sampler2D", required = false },
  { slot = "Normal", sampler = "Sampler2D", required = false },
  { slot = "Metallic", sampler = "Sampler2D", required = false },
  { slot = "Roughness", sampler = "Sampler2D", required = false },
  { slot = "Occlusion", sampler = "Sampler2D", required = false }
]
