schema = 1
id = "LitTextureArray"
name = "LitTextureArray"
source = "file"
usage = "General"
bootstrap = "None"
provider_policy = "GeometryOnly"

[transform]
source = "Vec3Position"
mapping = "Passthrough3D"
orientation = "World"
scale = "World"
projection = "WorldCameraVP"

[fragment]
source = "compositor/main_forward_surface.frag.glsl"
surface_module = "surface/material_surface.glsl"
material_source_module = "material/pbr_texturearray_source.glsl"
ntb_module = "ntb/ntb_texturearray_normalmap.glsl"

[compositor]
surface = "Lit"
blend = "Opaque"
pass = "ForwardOpaque"

[vertex]
requirements = ["Position", "UV0", "Normal"]
varyings = ["emit_data_index_id", "emit_texture_layer_id", "texture_layer_id_uses_data_index", "emit_world_pos", "emit_world_normal", "emit_uv0"]

[resources]
ubos = ["ViewportInfo", "CameraInfo", "SkyInfo"]
