schema = 2
id = "LitTextureArray"
name = "LitTextureArray"
source = "file"
bootstrap = "None"
provider_policy = "GeometryOnly"

[pipeline]
family = "forward_lit"
profiles = ["pbr_ibl_rgba16f2"]
default_profile = "pbr_ibl_rgba16f2"

[transform]
source = "Vec3Position"
mapping = "Passthrough3D"
orientation = "World"
scale = "World"
projection = "WorldCameraVP"

[fragment]
source = "forward_surface"
surface_module = "surface/material_surface.glsl"
material_source_module = "material/pbr_texturearray_source.glsl"
ntb_module = "ntb/ntb_texturearray_normalmap.glsl"

[compositor]
surface = "Lit"
blend = "Opaque"
pass = "ForwardOpaque"

[vertex]
requirements = ["Position", "UV0", "Normal"]
varyings = ["emit_data_index_id", "emit_world_pos", "emit_world_normal", "emit_uv0"]

[resources]
ubos = ["CameraInfo", "SkyInfo"]
samplers = ["Trilinear", "Linear"]
