schema = 2
id = "builtin/pure_color"
name = "builtin/pure_color"
source = "file"
bootstrap = "PureColor"
provider_policy = "GeometryOnly"

[pipeline]
family = "forward_unlit"
profiles = ["pure_color"]
default_profile = "pure_color"

[transform]
source = "Vec3Position"
mapping = "Passthrough3D"
orientation = "World"
scale = "World"
projection = "WorldCameraVP"

[fragment]
source = "forward_surface"
surface_module = "surface/material_surface.glsl"
material_source_module = "material/unlit_source.glsl"

[compositor]
surface = "Unlit"
blend = "Opaque"
pass = "ForwardOpaque"

[vertex]
requirements = ["Position"]
varyings = ["emit_data_index_id"]

[resources]
ubos = ["CameraInfo"]
material_data = { type = "EmissiveSurface" }
