schema = 1
id = "SkyMinimal"
name = "SkyMinimal"
source = "file"
usage = "Sky"
bootstrap = "None"
program_mode = "Compositor"
provider_policy = "GeometryOnly"

[transform]
source = "Vec3Position"
mapping = "Passthrough3D"
orientation = "World"
scale = "World"
projection = "WorldCameraVP"

[fragment]
source = "compositor/main_forward_sky.frag.glsl"
surface_module = "surface/sky_minimal_surface.glsl"

[compositor]
surface = "Sky"
blend = "Opaque"
pass = "ForwardOpaque"

[vertex]
requirements = ["Position"]
varyings = ["emit_frag_direction"]

[resources]
ubos = ["ViewportInfo", "CameraInfo", "SkyInfo"]
