schema = 1
id = "Texture2DArray"
name = "Texture2DArray"
source = "file"
usage = "General"
bootstrap = "None"
program_mode = "DirectInclude"
provider_policy = "GeometryOnly"

[transform]
source = "Vec2Position"
mapping = "NDCLift"
orientation = "World"
scale = "World"
projection = "LocalToWorldOnly"

[fragment]
source = "2d/recttexture2darray.frag.glsl"

[vertex]
requirements = ["Position", "UV0"]
varyings = ["emit_data_index_id", "emit_uv0"]

[resources]
ubos = ["ViewportInfo"]
ssbos = [{ name = "mtl", type = "TextureRectArraySurface" }]
textures = [{ slot = "BaseColor", sampler = "Sampler2DArray", required = true }]
