schema = 1
id = "builtin/text"
name = "Text2D"
source = "file"
usage = "General"
bootstrap = "TextAlphaBlend"
provider_policy = "GeometryOnly"

[transform]
source = "Vec2Position"
mapping = "PixelToLocal"
orientation = "World"
scale = "World"
projection = "OrthoViewport"

[fragment]
source = "compositor/main_forward_surface.frag.glsl"
surface_module = "surface/material_surface.glsl"
material_source_module = "material/text_source.glsl"

[compositor]
surface = "Unlit"
blend = "Opaque"
pass = "ForwardOpaque"

[vertex]
requirements = ["Position", "UV0"]
varyings = ["emit_data_index_id", "emit_uv0"]

[resources]
ubos = ["ViewportInfo"]
ssbos = [{ name = "mtl", type = "TransmissionSurface" }]
samplers = ["Nearest"]
