schema = 1
id = "Texture2DArray"
name = "Texture2DArray"
source = "file"
bootstrap = "None"
provider_policy = "GeometryOnly"

[transform]
source = "Vec2Position"
mapping = "NDCLift"
orientation = "World"
scale = "World"
projection = "LocalToWorldOnly"

[fragment]
source = "compositor/main_forward_surface.frag.glsl"
surface_module = "surface/material_surface.glsl"
material_source_module = "material/texture_array_source.glsl"

[compositor]
surface = "Unlit"
blend = "Opaque"
pass = "ForwardOpaque"

[vertex]
requirements = ["Position", "UV0"]
varyings = ["emit_data_index_id", "emit_uv0"]

[resources]
ssbos = [{ name = "mtl", type = "TextureRectArraySurface" }]
textures = [{ name = "base_color", sampler = "Sampler2DArray", required = true }]
samplers = ["Trilinear"]
