schema = 1
id = "Texture2DArray"
name = "Texture2DArray"
source = "file"
usage = "General"
bootstrap = "None"
program_mode = "Compositor"
provider_policy = "GeometryOnly"

[transform]
source = "Vec2Position"
mapping = "NDCLift"
orientation = "World"
scale = "World"
projection = "LocalToWorldOnly"

[fragment]
source = "compositor/main_forward_unlit_texture.frag.glsl"
surface_module = "surface/unlit_2darray_surface.glsl"

[compositor]
surface = "Unlit"
blend = "Opaque"
pass = "ForwardOpaque"

[vertex]
requirements = ["Position", "UV0"]
varyings = ["emit_data_index_id", "emit_texture_layer_id", "emit_uv0"]

[resources]
ubos = ["ViewportInfo"]
ssbos = [{ name = "mtl", type = "TextureRectArraySurface" }]
textures = [{ slot = "BaseColor", sampler = "Sampler2DArray", required = true }]
