schema = 3
id = "UnlitTextureArray"
name = "UnlitTextureArray"
source = "file"
bootstrap = "None"
provider_policy = "GeometryOnly"

[transform]
source = "Vec2Position"
mapping = "NDCLift"
orientation = "World"
scale = "World"
projection = "LocalToWorldOnly"

[fragment]
material_source_module = "material/unlit_texture_array_source.glsl"

[vertex]
requirements = ["Position", "UV0"]
varyings = ["emit_data_index_id", "emit_uv0"]

[resources]
textures = [{ name = "base_color", sampler = "Sampler2DArray", required = true }]
samplers = ["Trilinear"]
