schema = 1
id = "UnlitTexture"
name = "UnlitTexture"
source = "file"
usage = "General"
bootstrap = "None"
program_mode = "DirectInclude"
provider_policy = "GeometryOnly"

[transform]
source = "Vec2Position"
mapping = "NDCLift"
orientation = "World"
scale = "World"
projection = "LocalToWorldOnly"

[fragment]
source = "2d/puretexture2d.frag.glsl"

[vertex]
requirements = ["Position", "UV0"]
varyings = ["emit_uv0"]

[resources]
ubos = ["ViewportInfo"]
textures = [{ slot = "BaseColor", sampler = "Sampler2D", required = true }]
