schema = 1
id = "UnlitTexture"
name = "UnlitTexture"
source = "file"
bootstrap = "None"
provider_policy = "GeometryOnly"

[transform]
source = "Vec2Position"
mapping = "NDCLift"
orientation = "World"
scale = "World"
projection = "LocalToWorldOnly"

[fragment]
source = "compositor/main_forward_surface.frag.glsl"
surface_module = "surface/material_surface.glsl"
material_source_module = "material/texture_source.glsl"

[compositor]
surface = "Unlit"
blend = "Opaque"
pass = "ForwardOpaque"

[vertex]
requirements = ["Position", "UV0"]
varyings = ["emit_data_index_id", "emit_uv0"]

[resources]
textures = [{ name = "base_color", sampler = "Sampler2D", required = true }]
samplers = ["Trilinear"]
