schema = 1
id = "VertexLuminance"
name = "VertexLuminance"
source = "file"
usage = "General"
bootstrap = "None"
program_mode = "Compositor"
provider_policy = "GeometryOnly"

[transform]
source = "Vec3Position"
mapping = "Passthrough3D"
orientation = "World"
scale = "World"
projection = "WorldCameraVP"

[fragment]
source = "compositor/main_forward_surface.frag.glsl"
surface_module = "surface/material_surface.glsl"
material_source_module = "material/luminance_source.glsl"

[compositor]
surface = "Unlit"
blend = "Opaque"
pass = "ForwardOpaque"

[vertex]
requirements = ["Position", "Luminance"]
varyings = ["emit_data_index_id", "emit_texture_layer_id", "texture_layer_id_uses_data_index", "emit_luminance"]

[resources]
ubos = ["ViewportInfo", "CameraInfo"]
ssbos = [{ name = "mtl", type = "EmissiveSurface" }]
