schema = 1
id = "VertexLuminance"
name = "VertexLuminance"
source = "file"
bootstrap = "None"
provider_policy = "GeometryOnly"

[transform]
source = "Vec3Position"
mapping = "Passthrough3D"
orientation = "World"
scale = "World"
projection = "WorldCameraVP"

[fragment]
source = "forward_surface"
surface_module = "surface/material_surface.glsl"
material_source_module = "material/luminance_source.glsl"

[compositor]
surface = "Unlit"
blend = "Opaque"
pass = "ForwardOpaque"

[vertex]
requirements = ["Position", "Luminance"]
varyings = ["emit_data_index_id", "emit_luminance"]

[resources]
ubos = ["CameraInfo"]
material_data = { type = "EmissiveSurface" }
