// GENERATED by DescriptorMacroGen — DO NOT EDIT
// 数值真源：inc/hgl/common/DescriptorSetTypeDef.h（SceneBinding 枚举 + kDescriptorBindingMacros 规范表）
// 重新生成：DescriptorMacroGen --emit > ShaderLibrary/common/descriptor_macros.glsl
// @ulre begin
// @ulre name descriptor_macros
// @ulre kind Utility
// @ulre priority 0
// @ulre end
// descriptor_macros.glsl — 标准描述符集/绑定宏定义
//
// 默认值对应标准布局（Scene=0, Bindless=1；b3 集号收敛，PerObject 已退场）。
// 2D 生成器或自定义材质可在 #include 之前 #define 覆盖默认值。
//
// 固定布局：set 间按 Scene(0) < Bindless(1)。
// 行表（mtl_data_addrs / l2w / mesh_draw_params / 文本三表）已 BDA 化：
// 地址经 pc_root push constant + buffer_reference 寻址，无描述符声明
//（不在此定义任何默认绑定值）。
// 材质实例 mtl SSBO 的 struct/buffer 声明同样由 CompileMaterial 统一生成并注入。

#ifndef DESCRIPTOR_MACROS_GLSL
#define DESCRIPTOR_MACROS_GLSL

// ── Descriptor Set 索引 ──

#ifndef SCENE_SET
#define SCENE_SET 0
#endif

// ── Scene set ──

#ifndef CAMERA_BINDING
#define CAMERA_BINDING 0
#endif

#ifndef SKY_BINDING
#define SKY_BINDING 1
#endif

#ifndef VIEWPORT_BINDING
#define VIEWPORT_BINDING 2
#endif

#ifndef COLOR_PALETTE_BINDING
#define COLOR_PALETTE_BINDING 3
#endif

#ifndef BINDLESS_SET
#define BINDLESS_SET 1
#endif

#endif // DESCRIPTOR_MACROS_GLSL
