#ifndef HGL_GRAPH_SHADER_NODE_DEFINE_INCLUDE
#define HGL_GRAPH_SHADER_NODE_DEFINE_INCLUDE

#include<hgl/graph/shader/common.h>

SHADER_NODE_NAMESPACE_BEGIN
class Bool
{
public:


};//class Bool
SHADER_NODE_NAMESPACE_END
#endif//HGL_GRAPH_SHADER_NODE_DEFINE_INCLUDE
