#ifndef HGL_GRAPH_SHADER_NODE_DEFINE_INCLUDE
#define HGL_GRAPH_SHADER_NODE_DEFINE_INCLUDE

BEGIN_SHADER_NODE_NAMESPACE
class Bool
{
public:


};//class Bool
END_SHADER_NODE_NAMESPACE
#endif//HGL_GRAPH_SHADER_NODE_DEFINE_INCLUDE
